name: Build and Publish APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Write google-services.json
        run: |
          mkdir -p app
          cat <<'EOF' > app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF
      - name: Create tokens.xml
        run: |
          mkdir -p app/src/main/res/values
          cat <<EOF > app/src/main/res/values/tokens.xml
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
            <string name="firebase_web_client_id">${{ secrets.FIREBASE_WEB_CLIENT_ID }}</string>
          </resources>
          EOF
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon
      - name: Find generated APK
        id: find_apk
        run: |
          echo "Searching for APK..."
          APK_PATH=$(find app/build/outputs/apk -type f -name '*.apk' | head -n1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Create (or update) Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest APK
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_apk.outputs.apk_path }}
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
