name: Build and Publish APK

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      - name: Create tokens.xml
        run: |
          mkdir -p app/src/main/res/values
          echo '<?xml version="1.0" encoding="utf-8"?>' > app/src/main/res/values/tokens.xml
          echo '<resources>' >> app/src/main/res/values/tokens.xml
          echo "  <string name=\"firebase_web_client_id\">${{ secrets.FIREBASE_WEB_CLIENT_ID }}</string>" >> app/src/main/res/values/tokens.xml
          echo '</resources>' >> app/src/main/res/values/tokens.xml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Install GitHub CLI
        uses: cli/gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish APK to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest app/build/outputs/apk/release/app-release.apk --clobber 